name: Publish Docker image
on:
  release:
    types:
      - published

jobs:
  alpine-docker:
    name: Alpine - Push Docker image to Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile
          pull: true
          push: true
          tags: rytswd/testrepo:latest

  alpine-ghcr:
    name: Alpine - Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: rytswd
          password: ${{ secrets.CR_PAT }}
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine/Dockerfile
          pull: true
          push: true
          tags: rytswd/testrepo:latest
